pipeline {
    agent any
    
    stages {
        stage("Check Terraform Version"){
            steps{
                bat "terraform version"
            }
        }
        stage("Find Infrastructure"){
            steps{
                bat "cd infrastructure-code"
            }
        }
        stage("Terraform Initialize"){
            steps{
                bat "terraform validate"
            }
        }
        // stage("Terraform Validate"){
        //     steps{
        //         bat "terraform validate"
        //     }
        // }
        // stage("Terraform Plan"){
        //     steps{
        //         bat "terraform plan"
        //     }
        // }
    }
}