pipeline {
    agent any
    
    stages {
        stage("Check Terraform Version"){
            steps{
                bat "terraform version"
            }
        }
        stage("Find Terraform and Initialize"){
            steps{
                bat "cd infrastructure-code;terraform init"
            }
        }
        stage("Terraform Validate"){
            steps{
                bat "terraform validate"
            }
        }
        // stage("Terraform Plan"){
        //     steps{
        //         bat "terraform plan"
        //     }
        // }
    }
}